package main.Connection;

public enum MessageType {
    REQUEST_NICKNAME,
    NICKNAME_ACCEPTED,
    NICKNAME,
    NICKNAME_USED,
    USER_ADDED,
    DISABLE_USER,
    REMOVED_USER,
    PRIVATE_TEXT_MESSAGE,
    DIALOG_HISTORY,
    ALL_USERS
}
